### ISSUE TITLE
Document how to create a pypy3.7 environment

### ISSUE THREAD

**Issue by mattip** [conda-forge/pypy-meta-feedstock#11]
In #10, there is some confusion about the recommended way to create a pypy3.7 conda environment. Only the first of these works.
```
conda create -n pypy37 pypy3.7
conda create -n pypy37 pypy python=3.7
conda create -n pypy37 pypy pypy3.7
```

Once there is clarity on how this is supposed to work, we should update a document to reflect the new migration (thanks again for supporting this). What would be the logical place to document it?

**Comment by isuruf** [comment]
Looks like the pypy output in https://github.com/conda-forge/pypy-meta-feedstock/blob/master/recipe/meta.yaml#L50 doesn't have the `build: string` section like the others and therefore there's only one package for both 3.6 and 3.7 and the first to upload won.

**Comment by mattip** [comment]
xref gh-12 to add the build: string section

After that the correct invocation would be `conda create -n pypy37 pypy3.7 python=3.7` ?

**Comment by isuruf** [comment]
```
conda create -n pypy37 pypy python=3.7
conda create -n pypy37 pypy pypy3.7
conda create -n pypy37 python pypy3.7
```

All of the above should work now, but I would recommend the first option.

**Comment by beckermr** [comment]
Woops sorry to close this. I think github did it when I merged the PR above.

**Comment by isuruf** [comment]
@mattip, we can document this at https://github.com/conda-forge/conda-forge.github.io/blob/master/src/maintainer/knowledge_base.rst

**Comment by mattip** [comment]
Done, there is documentation now for users at https://conda-forge.org/docs/user/tipsandtricks.html#using-pypy-as-an-interpreter
