### ISSUE TITLE
PyPy 7.3.12 was released

### ISSUE THREAD

**Issue by swails** [conda-forge/pypy-meta-feedstock#29]
### Comment:

Hi!  The next version of PyPy (7.3.12) was released a couple months ago, and with it support for Python 3.10.

Are there any plans to create a new conda-forge package for Python 3.9/3.10 with this version of PyPy?  I'd likely be willing to assist here, although it looks like a steeper learning curve than other recipes I've contributed to in the past so I figured I'd see if someone more experienced with this recipe had plans to do another release.

**Comment by mattip** [comment]
See the PR at https://github.com/conda-forge/pypy3.6-feedstock/pull/105 to update 3.8 and 3.9 which is waiting on approval. There is not much enthusiasm for starting a pypy3.10 migration: it is not clear from the download numbers that the effort is justified.

**Comment by mattip** [comment]
CLosing, at this time there is not a plan to start a Pyython3.10 migration for PyPy.
